#### nginx
- name: install epel repository
  yum: name=http://ftp.riken.jp/Linux/fedora/epel/6/i386/epel-release-6-8.noarch.rpm state=present

- name: install nginx
  yum: name=nginx state=present

- name: nginx start
  service: name=nginx state=started enabled=yes

- name: copy index.html
  template: src=templates/nginx/index.html.j2 dest=/usr/share/nginx/html/index.html mode=0644
